import Foundation

class QuestionBank {
    
    var list = [Question]()
    
    init(){
        
        list.append(Question(text: "Ved rekonstruktion af knoglevæv forstås: nedbrydning af gamle lamelsystemer og dannelse af nye ", correctAnswer: true))
        list.append(Question(text: "Fibrocartilago findes i næsebruske", correctAnswer: false))
        list.append(Question(text: "Knogler vokser i tykkelse ved at der stadig sker en rekonstruktion ", correctAnswer: false))
        list.append(Question(text: "Periost har betydning for heling af knoglebrud", correctAnswer: true))
        list.append(Question(text: "En Haversk lamel består af kollagene fibriler", correctAnswer: true))
        list.append(Question(text: "Hyalinbrusk danner alle disci og menisi", correctAnswer: false))
        list.append(Question(text: "Osteon er en vævsstruktur, der blandt andet indeholder: at Haversk lamelsystem", correctAnswer: true))
        list.append(Question(text: "For knoglematrix gælder at dets grundsubstans indeholder kalksalte", correctAnswer: true))
        
        list.append(Question(text: "Om læderhuden gælder, at den består af bindevæv, der er uorganiseret", correctAnswer: true))
        list.append(Question(text: "Om læderhuden gælder, at den består af bindevæv, der er kollagent fast", correctAnswer: true))
        list.append(Question(text: " Om læderhuden gælder, at den består af bindevæv, der er cellulært", correctAnswer: false))
        list.append(Question(text: " Om læderhuden gælder, at den består af bindevæv, der er organiseret", correctAnswer: false))
        list.append(Question(text: " Om læderhuden gælder, at den består af bindevæv, der er løst", correctAnswer: false))
        
        list.append(Question(text: " Anastomoser mellem bindevævsceller er sjældne. Anastomoserende bindevævsceller er reticulumceller", correctAnswer: true))
        list.append(Question(text: " Anastomoser mellem bindevævsceller er sjældne. Anastomoserende bindevævsceller er fibroblaster", correctAnswer: false))
        list.append(Question(text: " Anastomoser mellem bindevævsceller er sjældne. Anastomoserende bindevævsceller er plasmaceller", correctAnswer: false))
        list.append(Question(text: " Anastomoser mellem bindevævsceller er sjældne. Anastomoserende bindevævsceller er makrofager", correctAnswer: false))
        list.append(Question(text: " Anastomoser mellem bindevævsceller er sjældne. Anastomoserende bindevævsceller er udifferentierede mesenchymceller", correctAnswer: false))
        
        list.append(Question(text: " Til de runde bindevævsceller hører mastceller", correctAnswer: true))
        list.append(Question(text: " Til de runde bindevævsceller hører plasmaceller", correctAnswer: true))
        list.append(Question(text: " Til de runde bindevævsceller hører fibroblaster ", correctAnswer: false))
        list.append(Question(text: " Til de runde bindevævsceller hører makroflager", correctAnswer: false))
        
        list.append(Question(text: " Fælles for læderhud og sener er, at de består af bindevæv, der er kollagent", correctAnswer: true))
        list.append(Question(text: " Fælles for læderhud og sener er, at de består af bindevæv, der er fast", correctAnswer: true))
        list.append(Question(text: " Fælles for læderhud og sener er, at de består af bindevæv, der er uorganiseret", correctAnswer: false))
        list.append(Question(text: " Fælles for læderhud og sener er, at de består af bindevæv, der er organiseret", correctAnswer: false))
        list.append(Question(text: " Fælles for læderhud og sener er, at de består af bindevæv, der er cellulært", correctAnswer: false))
        
        list.append(Question(text: " Fælles for støttevæv og epitelvæv er, at begge indeholder celler", correctAnswer: true))
        list.append(Question(text: " Fælles for støttevæv og epitelvæv er, at begge beklæder ledhulernes vægge", correctAnswer: false))
        list.append(Question(text: " Fælles for støttevæv og epitelvæv er, at begge mangler kar", correctAnswer: false))
        list.append(Question(text: " Fælles for støttevæv og epitelvæv er, at begge omfatter elastiske fibriller", correctAnswer: false))
        list.append(Question(text: " Fælles for støttevæv og epitelvæv er, at begge omfatter kollagene fibriller", correctAnswer: false))
        
        list.append(Question(text: " Sener består af bindevæv, der er faste", correctAnswer: true))
        list.append(Question(text: " Sener består af bindevæv, der er organiseret", correctAnswer: true))
        list.append(Question(text: " Sener består af bindevæv, der er uorganiseret", correctAnswer: false))
        list.append(Question(text: " Sener består af bindevæv, der er cellulært", correctAnswer: false))
        list.append(Question(text: " Sener består af bindevæv, der er elastisk", correctAnswer: false))
        
        list.append(Question(text: " Fælles for sener og læderhud er at begge består af bindevæv, der hedder fibrillært kollagent løst", correctAnswer: false))
        list.append(Question(text: " Fælles for sener og læderhud er at begge består af bindevæv, der hedder fast organiseret", correctAnswer: false))
        list.append(Question(text: " Fælles for sener og læderhud er at begge består af bindevæv, der hedder fast uorganiseret", correctAnswer: false))
        list.append(Question(text: " Fælles for sener og læderhud er at begge består af bindevæv, der hedder fibrillært elastisk", correctAnswer: false))
        
        list.append(Question(text: " Mesenchym er fællesnavn for mesotel og endotel", correctAnswer: false))
        list.append(Question(text: " Mesenchym består af enlaget pladeepitel", correctAnswer: false))
        list.append(Question(text: " Mesenchym udgør hovedbestanddelen af sener", correctAnswer: false))
        list.append(Question(text: " Mesenchym mangler celler", correctAnswer: false))
        list.append(Question(text: " Mesenchym er embryonalt bindevæv", correctAnswer: true))
        
        list.append(Question(text: " Retikulintråde er fællesnavn for kollagene og elastiske fibriller", correctAnswer: false))
        list.append(Question(text: " Retikulintråde anses for at være umodne elastiske fibriller", correctAnswer: false))
        list.append(Question(text: " Retikulintråde findes omkring blodkar", correctAnswer: true))
        list.append(Question(text: " Retikulintråde træffes i retikulært bindevæv", correctAnswer: true))
        list.append(Question(text: " Retikulintråde er bygget som elastiske fibriller", correctAnswer: false))
        
        list.append(Question(text: " Om bindevævsceller gælder at udifferentierede mesenchymceller er stopfyldt med korn i cytoplasma", correctAnswer: false))
        list.append(Question(text: " Om bindevævsceller gælder at fedtceller har kernen liggende midt i cellen", correctAnswer: false))
        list.append(Question(text: " Om bindevævsceller gælder at plasmaceller danner fibriller", correctAnswer: false))
        list.append(Question(text: " Om bindevævsceller gælder at mastceller er reserveceller ", correctAnswer: false))
        list.append(Question(text: " Om bindevævsceller gælder at makrofager fagocyterer", correctAnswer: true))
        
        list.append(Question(text: " Til de stjerneformede bindevævsceller hører fibroblaster ", correctAnswer: true))
        list.append(Question(text: " Til de stjerneformede bindevævsceller hører fedtceller", correctAnswer: false))
        list.append(Question(text: " Til de stjerneformede bindevævsceller hører plasmaceller ", correctAnswer: false))
        list.append(Question(text: " Til de stjerneformede bindevævsceller hører mastceller", correctAnswer: false))
        list.append(Question(text: " Til de stjerneformede bindevævsceller hører makrofager ", correctAnswer: true))
      
        
        list.append(Question(text: " Bevægelige cytoplasmaudløbere kan bevæge et slimtæppe ", correctAnswer: true))
        list.append(Question(text: " Bevægelige cytoplasmaudløbere har især betydning for resorption ", correctAnswer: false))
        list.append(Question(text: " Bevægelige cytoplasmaudløbere forekommer altid på flerlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Bevægelige cytoplasmaudløbere kaldes sansehår ", correctAnswer: false))
        list.append(Question(text: " Bevægelige cytoplasmaudløbere findes i luftvejene ", correctAnswer: true))
        
        list.append(Question(text: " Om overgangsepitel gælder, at det findes i urinblæren", correctAnswer: true))
        list.append(Question(text: " Om overgangsepitel gælder, at alle dets celler står på basalmembranen", correctAnswer: false))
        list.append(Question(text: " Om overgangsepitel gælder, at dets overflade dannes af kubiske celler", correctAnswer: true))
        list.append(Question(text: " Om overgangsepitel gælder, at omkring halvdelen af dets celler er forhornede", correctAnswer: false))
        list.append(Question(text: " Om overgangsepitel gælder, at det er velegnet til resorption", correctAnswer: false))

        
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, cellerne har forskellig højde ", correctAnswer: false))
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, kun nogle af cellerne når basalmembranen", correctAnswer: true))
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, det drejer sig om pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, kernerne ligger i flere rækker", correctAnswer: false))
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, kun nogle af cellerne når lumen ", correctAnswer: false))
        
        list.append(Question(text: " Overgangsepitel findes i, arterier ", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel findes i, urinblære", correctAnswer: true))
        list.append(Question(text: " Overgangsepitel findes i, kun nogle af cellerne når lumen ", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel findes i, mundhule", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel findes i, tarm ", correctAnswer: false))
        
        list.append(Question(text: " På figuren ses, endotel", correctAnswer: true))
        list.append(Question(text: " På figuren ses, flerlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " På figuren ses, enlaget kubisk epitel ", correctAnswer: false))
        list.append(Question(text: " På figuren ses, enlaget pladeepitel", correctAnswer: true))
        list.append(Question(text: " På figuren ses, mesotel ", correctAnswer: false))
        
        list.append(Question(text: " Dækepitel i, seneskeder er flerlaget pladeepitel  ", correctAnswer: false))
        list.append(Question(text: " Dækepitel i, tarmen er forsynet med fimrehår  ", correctAnswer: false))
        list.append(Question(text: " Dækepitel i, luftvejene er forsynet med kinocilier ", correctAnswer: true))
        list.append(Question(text: " Dækepitel i, urinblæren hedder mesotel ", correctAnswer: false))
        list.append(Question(text: " Dækepitel i, mundhulen kaldes endotel  ", correctAnswer: false))
        
        list.append(Question(text: " Epitelbeklædningen i, blærens væg er overgangsepitel", correctAnswer: true))
        list.append(Question(text: " Epitelbeklædningen i, mundhulen er flerlaget pladeepitel", correctAnswer: true))
        list.append(Question(text: " Epitelbeklædningen i, karvægge kaldes mesotel ", correctAnswer: false))
        list.append(Question(text: " Epitelbeklædningen i, ledhuler hedder endotel ", correctAnswer: false))
        list.append(Question(text: " Epitelbeklædningen i, tarmen er forsynet med kinocilier ", correctAnswer: false))
        
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, bindevævet under dækepitel", correctAnswer: true))
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, den uforhornede del af flerlaget pladeepitel, hvor de overfladiske lag er forhornede  ", correctAnswer: false))
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, alle lag i flerlaget pladeepitel uden forhorning ", correctAnswer: false))
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, tarmepitel af hensyn til den stærke resorption af næringsstoffer ", correctAnswer: false))
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, prismatisk epitel med livlig cilievirksomhed ", correctAnswer: false))
        
        list.append(Question(text: " Epitelvæv inddeles efter, funktion", correctAnswer: true))
        list.append(Question(text: " Epitelvæv inddeles efter, cellernes antal ", correctAnswer: false))
        list.append(Question(text: " Epitelvæv inddeles efter, cellernes form ", correctAnswer: false))
        list.append(Question(text: " Epitelvæv inddeles efter, cellernes størrelse ", correctAnswer: false))
        list.append(Question(text: " Epitelvæv inddeles efter, kernernes lejring ", correctAnswer: false))
        
        list.append(Question(text: " Dækepitelet i tarmen, består udelukkende af pladeformede celler ", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, er særlig egnet til resorption", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, bærer kinocilier ", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, er flerlaget  ", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, kaldes mesotel ", correctAnswer: false))
        
        list.append(Question(text: " Mesotel, består af prismatiske celler ", correctAnswer: false))
        list.append(Question(text: " Mesotel, ernæres fra det underliggende bindevæv", correctAnswer: true))
        list.append(Question(text: " Mesotel, bærer fimrehår ", correctAnswer: false))
        list.append(Question(text: " Mesotel, findes i blodkar ", correctAnswer: false))
        list.append(Question(text: " Mesotel, beklæder væggene i luftvejene ", correctAnswer: false))
        
        list.append(Question(text: " Flerlaget pladeepitel findes, i oesophagus", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes, i oesophagus", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes, i oesophagus", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes, i oesophagus", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes, i oesophagus", correctAnswer: false))
        
        list.append(Question(text: " På tegningen ses, en ekstraepitelial kirtel", correctAnswer: true))
        list.append(Question(text: " På tegningen ses, flere bægerceller markeret (1) ", correctAnswer: false))
        list.append(Question(text: " På tegningen ses, flerlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " På tegningen ses, en intra-dækepitelial kirtel", correctAnswer: true))
        list.append(Question(text: " På tegningen ses, unicellulære kirtler ", correctAnswer: false))
        
        list.append(Question(text: " Dækepitel inddeles efter, epitelcellernes lejring", correctAnswer: true))
        list.append(Question(text: " Dækepitel inddeles efter, epitelcellernes form", correctAnswer: true))
        list.append(Question(text: " Dækepitel inddeles efter, epitelcellernes evne til at ændre form ", correctAnswer: false))
        list.append(Question(text: " Dækepitel inddeles efter, kernernes lejring i de enkelte celler ", correctAnswer: false))
        list.append(Question(text: " Dækepitel inddeles efter, kernernes størrelse ", correctAnswer: false))
        
        list.append(Question(text: " Det bindevæv, der ligger under ,dækepitel, mangler nerver ", correctAnswer: false))
        list.append(Question(text: " Det bindevæv, der ligger under ,dækepitel, støtter epitelet ", correctAnswer: true))
        list.append(Question(text: " Det bindevæv, der ligger under ,dækepitel, danner nye epitelceller til erstatning af afslidte ", correctAnswer: false))
        list.append(Question(text: " Det bindevæv, der ligger under ,dækepitel, ernærer epitelet ", correctAnswer: false))
        list.append(Question(text: " På figuren ses, prismatisk epitel  ", correctAnswer: true))
        list.append(Question(text: " På figuren ses, tarmepitel ", correctAnswer: false))
        list.append(Question(text: " På figuren ses, stereocilier ", correctAnswer: true))
        list.append(Question(text: " På figuren ses, bægerceller ", correctAnswer: false))
        list.append(Question(text: " På figuren ses, kinocilier ", correctAnswer: false))
        
        list.append(Question(text: " Bevægelige cytoplasmaudløbere, kaldes sansehår  ", correctAnswer: false))
        list.append(Question(text: " Bevægelige cytoplasmaudløbere, har især betydning for resorption ", correctAnswer: false))
        list.append(Question(text: " Bevægelige cytoplasmaudløbere, kan bevæge et slimtæppe ", correctAnswer: true))
        list.append(Question(text: " Bevægelige cytoplasmaudløbere, forekommer altid på flerlaget pladeepitel", correctAnswer: false))
        list.append(Question(text: " Bevægelige cytoplasmaudløbere, findes i luftvejene", correctAnswer: true))
        
        list.append(Question(text: " Enlaget pladeepitel, findes i kar", correctAnswer: true))
        list.append(Question(text: " Enlaget pladeepitel, beklæder indsiden af luftrøret ", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, er epitelet i mundhulen ", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, kan være flerradet ", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, består af celler, der alle er flade ", correctAnswer: true))
        
        list.append(Question(text: " Figuren viser et epitel, der, er udstyret med kinocilier ", correctAnswer: true))
        list.append(Question(text: " Figuren viser et epitel, der, mangler bægerceller ", correctAnswer: false))
        list.append(Question(text: " Figuren viser et epitel, der, har fimrehår ", correctAnswer: true))
        list.append(Question(text: " Figuren viser et epitel, der, er flerlaget ", correctAnswer: false))
        list.append(Question(text: " Figuren viser et epitel, der, findes i tyndtarmen ", correctAnswer: false))
        
        list.append(Question(text: " Om fimrehår gælder, at de, kan bevæge et slimtæppe  ", correctAnswer: true))
        list.append(Question(text: " Om fimrehår gælder, at de, mangler i mundhulen ", correctAnswer: true))
        list.append(Question(text: " Om fimrehår gælder, at de, findes i tarmen ", correctAnswer: false))
        list.append(Question(text: " Om fimrehår gælder, at de, har betydning for resorption ", correctAnswer: false))
        list.append(Question(text: " Om fimrehår gælder, at de, fremmer sekretion ", correctAnswer: false))
        
        list.append(Question(text: " Overgangsepitel, forhorner altid i de overfladiske lag ", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel, beklæder hele tarmkanalen ", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel, består udelukkende af kubiske celler ", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel, er særlig velegnet til at resorbere ", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel, er flerlaget kubisk epitel ", correctAnswer: true))
        
        list.append(Question(text: " Flerlaget pladeepitel findes på steder, hvor overfladen påvirkes af, urin ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes på steder, hvor overfladen påvirkes af, slid ", correctAnswer: true))
        list.append(Question(text: " Flerlaget pladeepitel findes på steder, hvor overfladen påvirkes af, tarmsaft ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes på steder, hvor overfladen påvirkes af, blod og lymfe  ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes på steder, hvor overfladen påvirkes af, stærk syre", correctAnswer: false))
        
        list.append(Question(text: " Dækepitel inddeles efter, kernernes lejring i cellerne", correctAnswer: false))
        list.append(Question(text: " Dækepitel inddeles efter, cellernes lejring", correctAnswer: true))
        list.append(Question(text: " Dækepitel inddeles efter, kernernes farvbarhed ", correctAnswer: false))
        list.append(Question(text: " Dækepitel inddeles efter, cellernes form ", correctAnswer: true))
        list.append(Question(text: " Dækepitel inddeles efter, cellernes regenerationsevne ", correctAnswer: false))
        
        list.append(Question(text: " Om fimrehår gælder, at de, kan bevæge et slimtæppe ", correctAnswer: true))
        list.append(Question(text: " Om fimrehår gælder, at de, mangler i mundhulen ", correctAnswer: true))
        list.append(Question(text: " Om fimrehår gælder, at de, findes i tarmen ", correctAnswer: false))
        list.append(Question(text: " Om fimrehår gælder, at de, har betydning for resorption ", correctAnswer: false))
        list.append(Question(text: " Om fimrehår gælder, at de, fremmer sekretion ", correctAnswer: false))
        
        list.append(Question(text: " Enlaget, flerradet prismatisk epitel består af celler, der, har alle kerner basalt ", correctAnswer: false))
        list.append(Question(text: " Enlaget, flerradet prismatisk epitel består af celler, der, har alle kerner luminalt ", correctAnswer: false))
        list.append(Question(text: " Enlaget, flerradet prismatisk epitel består af celler, der, alle når lumen", correctAnswer: false))
        list.append(Question(text: " Enlaget, flerradet prismatisk epitel består af celler, der, alle når basalmembranen ", correctAnswer: true))
        list.append(Question(text: " Enlaget, flerradet prismatisk epitel består af celler, der, har kerner lejret i forskellig højde", correctAnswer: true))
        
        list.append(Question(text: " I dækepitel findes, blodkapillærer ", correctAnswer: false))
        list.append(Question(text: " I dækepitel findes, små vener (venoler)  ", correctAnswer: false))
        list.append(Question(text: " I dækepitel findes, små arterier (arterioler) ", correctAnswer: false))
        list.append(Question(text: " I dækepitel findes, lymfekapillærer  ", correctAnswer: false))
        list.append(Question(text: " I dækepitel findes, fine nervetråde", correctAnswer: true))
        
        list.append(Question(text: " Dækepitelet i tarmen, består kun af et lag celler ", correctAnswer: true))
        list.append(Question(text: " Dækepitelet i tarmen, er forsynet med kinocilier ", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, kaldes overgangsepitel ", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, består af prismatiske celler ", correctAnswer: true))
        list.append(Question(text: " Dækepitelet i tarmen, er kroppens mest modstandsdygtige epitel mod mekanisk påvirkning ", correctAnswer: false))
        
        list.append(Question(text: " For enlaget pladeepitel gælder at, en del af cellerne kan forhorne ", correctAnswer: false))
        list.append(Question(text: " For enlaget pladeepitel gælder at, de fleste celler overlapper hinanden ", correctAnswer: false))
        list.append(Question(text: " For enlaget pladeepitel gælder at, alle celler er pladeformede", correctAnswer: true))
        list.append(Question(text: " For enlaget pladeepitel gælder at, det forekommer som endotel", correctAnswer: true))
        list.append(Question(text: " For enlaget pladeepitel gælder at, kun nogle af cellerne står på basalmembranen ", correctAnswer: false))
        
        list.append(Question(text: " Fælles for et enlaget enradet prismatisk epitel og et enlaget flerradet prismatisk epitel er, at begge, kan forhorne ", correctAnswer: false))
        list.append(Question(text: " Fælles for et enlaget enradet prismatisk epitel og et enlaget flerradet prismatisk epitel er, at begge, er særlig modstandsdygtige mod slid ", correctAnswer: false))
        list.append(Question(text: " Fælles for et enlaget enradet prismatisk epitel og et enlaget flerradet prismatisk epitel er, at begge, beklæder urinblærens indside ", correctAnswer: false))
        list.append(Question(text: " Fælles for et enlaget enradet prismatisk epitel og et enlaget flerradet prismatisk epitel er, at begge, ernæres fra det underliggende bindevæv ", correctAnswer: true))
        list.append(Question(text: " Fælles for et enlaget enradet prismatisk epitel og et enlaget flerradet prismatisk epitel er, at begge, findes i karvægge ", correctAnswer: false))
        
        list.append(Question(text: " I mundhulen findes epitel, der kaldes, kubisk ", correctAnswer: false))
        list.append(Question(text: " I mundhulen findes epitel, der kaldes, kubisk ", correctAnswer: false))
        list.append(Question(text: " I mundhulen findes epitel, der kaldes, kubisk ", correctAnswer: false))
        list.append(Question(text: " I mundhulen findes epitel, der kaldes, kubisk ", correctAnswer: false))
        list.append(Question(text: " I mundhulen findes epitel, der kaldes, kubisk ", correctAnswer: false))
        
        list.append(Question(text: " Fælles for de to synsfelter er, at de begge, viser overfladeepitel  ", correctAnswer: true))
        list.append(Question(text: " Fælles for de to synsfelter er, at de begge, viser pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Fælles for de to synsfelter er, at de begge, viser væv med forhorning ", correctAnswer: false))
        list.append(Question(text: " Fælles for de to synsfelter er, at de begge, viser epitel med ringe resorptionsevne ", correctAnswer: true))
        list.append(Question(text: " Fælles for de to synsfelter er, at de begge, indeholder epitel, der kan transportere et slimtæppe ved hjælp af fimrehår", correctAnswer: false))
        
        list.append(Question(text: " I mundhulen findes et epitel, der, er forsynet med ubevægelige cytoplasmaudløbere ", correctAnswer: false))
        list.append(Question(text: " I mundhulen findes et epitel, der, mangler cilier  ", correctAnswer: true))
        list.append(Question(text: " I mundhulen findes et epitel, der, indeholder bægerceller  ", correctAnswer: false))
        list.append(Question(text: " I mundhulen findes et epitel, der, består af kubiske celler nærmest lumen", correctAnswer: false))
        list.append(Question(text: " I mundhulen findes et epitel, der, hedder flerlaget pladeepitel ", correctAnswer: true))
        
        list.append(Question(text: " Der kan være grund til at anvende betegnelsen flerradet om, flerlaget prismatisk epitel ", correctAnswer: false))
        list.append(Question(text: " Der kan være grund til at anvende betegnelsen flerradet om, overgangsepitel  ", correctAnswer: false))
        list.append(Question(text: " Der kan være grund til at anvende betegnelsen flerradet om, enlaget prismatisk epitel ", correctAnswer: true))
        list.append(Question(text: " Der kan være grund til at anvende betegnelsen flerradet om, flerlaget pladeepitel", correctAnswer: false))
        list.append(Question(text: " Der kan være grund til at anvende betegnelsen flerradet om, flerlaget kubisk epitel", correctAnswer: false))
        
        
        list.append(Question(text: " Epitelet i mundhulen, er vort mest plastiske epitel ", correctAnswer: false))
        list.append(Question(text: " Epitelet i mundhulen, er forsynet med ubevægelige udløbere ", correctAnswer: false))
        list.append(Question(text: " Epitelet i mundhulen, er flerlaget pladeepitel ", correctAnswer: true))
        list.append(Question(text: " Epitelet i mundhulen, består udelukkende af pladeformede celler ", correctAnswer: false))
        list.append(Question(text: " Epitelet i mundhulen, indeholder kapillærer i de uforhornede lag ", correctAnswer: false))
        
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, tarmepitel af hensyn til den stærke resorption af næringsstoffer", correctAnswer: false))
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, den uforhornede del af flerlaget pladeepitel, hvor de overfladiske lag er forhornede ", correctAnswer: false))
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, prismatisk epitel med livlig cilievirksomhed ", correctAnswer: false))
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, alle lag i flerlaget pladeepitel uden forhorning", correctAnswer: false))
        list.append(Question(text: " Fine blodkar (hårkar) og lymfekar findes i, bindevævet under dækepitel ", correctAnswer: true))
        
        list.append(Question(text: " Flerlaget pladeepitel findes i, luftrør ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes i, næsehule ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes i, mundhule  ", correctAnswer: true))
        list.append(Question(text: " Flerlaget pladeepitel findes i, tarm  ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel findes i, urinveje  ", correctAnswer: false))
        
        list.append(Question(text: " Dækepitel inddeles efter, epitelcellernes form ", correctAnswer: true))
        list.append(Question(text: " Dækepitel inddeles efter, epitelcellernes lejring ", correctAnswer: true))
        list.append(Question(text: " Dækepitel inddeles efter, kernernes lejring i de enkelte celler ", correctAnswer: false))
        list.append(Question(text: " Dækepitel inddeles efter, epitelcellernes evne til at ændre form", correctAnswer: false))
        list.append(Question(text: " Dækepitel inddeles efter, kernernes størrelse ", correctAnswer: false))
        
        list.append(Question(text: " Hvis bindevæv mangler under dækepitel, vil epitelet, gå i stykker ", correctAnswer: true))
        list.append(Question(text: " Hvis bindevæv mangler under dækepitel, omdannes til kirtelepitel ", correctAnswer: false))
        list.append(Question(text: " Hvis bindevæv mangler under dækepitel, forkalke  ", correctAnswer: false))
        list.append(Question(text: " Hvis bindevæv mangler under dækepitel, vil epitelet, forhorne  ", correctAnswer: false))
        list.append(Question(text: " Hvis bindevæv mangler under dækepitel, vil epitelet, danne rigelig intercellularsubstans ", correctAnswer: false))
        
        list.append(Question(text: " I luftvejene findes et epitel, der, er prismatisk", correctAnswer: true))
        list.append(Question(text: " I luftvejene findes et epitel, der, bærer ubevægelige cytoplasmaudløbere ", correctAnswer: false))
        list.append(Question(text: " I luftvejene findes et epitel, der, udelukkende består af secernerende celler ", correctAnswer: false))
        list.append(Question(text: " I luftvejene findes et epitel, der, minder stærkt om overgangsepitel ", correctAnswer: false))
        list.append(Question(text: " I luftvejene findes et epitel, der, er enlaget ", correctAnswer: true))
        
        list.append(Question(text: " Dækepitelet i tarmen, er enlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, kaldes overgangsepitel ", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, er forsynet med fimrehår ", correctAnswer: false))
        list.append(Question(text: " Dækepitelet i tarmen, er særlig egnet til opsugning ", correctAnswer: true))
        list.append(Question(text: " Dækepitelet i tarmen, består af flere lag celler ", correctAnswer: false))
        
        list.append(Question(text: " Flerlaget pladeepitel og enlaget flerradet prismatisk epitel har visse fællestræk. Begge, indeholder fine nervetråde ", correctAnswer: true))
        list.append(Question(text: " Flerlaget pladeepitel og enlaget flerradet prismatisk epitel har visse fællestræk. Begge, har alle celler stående på basalmembranen ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel og enlaget flerradet prismatisk epitel har visse fællestræk. Begge, kan forhorne ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel og enlaget flerradet prismatisk epitel har visse fællestræk. Begge, indeholder bægerceller ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel og enlaget flerradet prismatisk epitel har visse fællestræk. Begge, har kerner i flere rader ", correctAnswer: true))
        
        list.append(Question(text: " Transport af et slimtæppe ved hjælp af fimrehår finder sted i, urinleder ", correctAnswer: false))
        list.append(Question(text: " Transport af et slimtæppe ved hjælp af fimrehår finder sted i, mavesæk ", correctAnswer: false))
        list.append(Question(text: " Transport af et slimtæppe ved hjælp af fimrehår finder sted i, tyndtarm ", correctAnswer: false))
        list.append(Question(text: " Transport af et slimtæppe ved hjælp af fimrehår finder sted i, luftrør  ", correctAnswer: true))
        list.append(Question(text: " Transport af et slimtæppe ved hjælp af fimrehår finder sted i, tyktarm  ", correctAnswer: false))
        
        list.append(Question(text: " Fælles for endotel og mesotel er, at begge, består af kubiske celler med kerne ", correctAnswer: false))
        list.append(Question(text: " Fælles for endotel og mesotel er, at begge, består af flade celler uden kerne", correctAnswer: false))
        list.append(Question(text: " Fælles for endotel og mesotel er, at begge, er enlagede ", correctAnswer: true))
        list.append(Question(text: " Fælles for endotel og mesotel er, at begge, beklæder serøse hinder", correctAnswer: false))
        list.append(Question(text: " Fælles for endotel og mesotel er, at begge, findes i blodkar ", correctAnswer: false))
        
        list.append(Question(text: " I luftvejene findes et epitel, der, har kinocilier ", correctAnswer: true))
        list.append(Question(text: " I luftvejene findes et epitel, der, indeholder pladeformede celler ", correctAnswer: false))
        list.append(Question(text: " I luftvejene findes et epitel, der, er flerradet ", correctAnswer: true))
        list.append(Question(text: " I luftvejene findes et epitel, der, består af flere lag", correctAnswer: false))
        list.append(Question(text: " I luftvejene findes et epitel, der, har kubiske celler nærmest lumen ", correctAnswer: false))
        
        list.append(Question(text: " Kinocilier, er ubevægelige cytoplasmaudløbere ", correctAnswer: false))
        list.append(Question(text: " Kinocilier, transporterer ved egne bevægelser et slimtæppe", correctAnswer: true))
        list.append(Question(text: " Kinocilier, kan findes på alle celleflader ", correctAnswer: false))
        list.append(Question(text: " Kinocilier, bevæges af slimlaget på overfladen  ", correctAnswer: false))
        list.append(Question(text: " Kinocilier, bevæges af slimlaget på overfladen  ", correctAnswer: true))
        
        list.append(Question(text: " Om overgangsepitel gælder, at, det findes i urinblæren  ", correctAnswer:true))
        list.append(Question(text: " Om overgangsepitel gælder, at, omkring halvdelen af dets celler er forhornede", correctAnswer: false))
        list.append(Question(text: " Om overgangsepitel gælder, at, dets overflade dannes af kubiske celler ", correctAnswer: true))
        list.append(Question(text: " Om overgangsepitel gælder, at, det er velegnet til resorption ", correctAnswer: false))
        list.append(Question(text: " Om overgangsepitel gælder, at, alle dets celler står på basalmembranen ", correctAnswer: false))
        
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, cellerne har forskellig højde  ", correctAnswer: false))
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, kun nogle af cellerne når basalmembranen ", correctAnswer: true))
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, det drejer sig om pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, kun nogle af cellerne når lumen ", correctAnswer: false))
        list.append(Question(text: " Et dækepitel vil altid være flerlaget når, kernerne ligger i flere rækker ", correctAnswer: false))
        
        list.append(Question(text: " Enlaget kubisk epitel, består af terningelignende celler ", correctAnswer: true))
        list.append(Question(text: " Enlaget kubisk epitel, kan være flerradet ", correctAnswer: false))
        list.append(Question(text: " Enlaget kubisk epitel, beklæder væggene i små arterier ", correctAnswer: false))
        list.append(Question(text: " Enlaget kubisk epitel, kan forhorne ", correctAnswer: false))
        list.append(Question(text: " Enlaget kubisk epitel, er altid enradet ", correctAnswer: true))
        
        list.append(Question(text: " Det mest \"plastiske\" dækepitel er, enlaget kubisk epitel ", correctAnswer: false))
        list.append(Question(text: " Det mest \"plastiske\" dækepitel er, enlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Det mest \"plastiske\" dækepitel er, flerlaget pladeepitel uden forhorning ", correctAnswer: false))
        list.append(Question(text: " Det mest \"plastiske\" dækepitel er, prismatisk epitel med fimrehår ", correctAnswer: false))
        list.append(Question(text: " Det mest \"plastiske\" dækepitel er, overgangsepitel ", correctAnswer: true))
        
        list.append(Question(text: " Fælles for dækepitel og det underliggende bindevæv er, at begge, mangler kar ", correctAnswer: false))
        list.append(Question(text: " Fælles for dækepitel og det underliggende bindevæv er, indeholder nervetråde ", correctAnswer: true))
        list.append(Question(text: " Fælles for dækepitel og det underliggende bindevæv er, hører til støttevæv ", correctAnswer: false))
        list.append(Question(text: " Fælles for dækepitel og det underliggende bindevæv er, præges af celleprodukterne ", correctAnswer: false))
        list.append(Question(text: " Fælles for dækepitel og det underliggende bindevæv er, består af tætlejrede celler", correctAnswer: false))
        
        list.append(Question(text: " Enlaget pladeepitel, beklæder indsiden af seneskeder ", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, kan forhorne ", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, består af pladeformede celler med kerne", correctAnswer: true))
        list.append(Question(text: " Enlaget pladeepitel, danner væg i ledhuler ", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, består af kerneløse plader ", correctAnswer: false))
        
        list.append(Question(text: " Fælles for enlaget og flerlaget pladeepitel er, at begge former, udelukkende består af pladeformede celler ", correctAnswer: false))
        list.append(Question(text: " Fælles for enlaget og flerlaget pladeepitel er, at begge former, er velegnede til resorption ", correctAnswer: false))
        list.append(Question(text: " Fælles for enlaget og flerlaget pladeepitel er, at begge former, kan forhorne ", correctAnswer: false))
        list.append(Question(text: " Fælles for enlaget og flerlaget pladeepitel er, at begge former, beklæder serøse hinder ", correctAnswer: false))
        list.append(Question(text: " Fælles for enlaget og flerlaget pladeepitel er, at begge former, mangler hårkar ", correctAnswer: true))
        list.append(Question(text: " Hvilke(t) udsagn kan accepteres?, resorption i tarmen er knyttet til højt prismatisk epitel", correctAnswer: true))
        list.append(Question(text: " Hvilke(t) udsagn kan accepteres?, overgangsepitel findes på de steder i mundhulen, hvor slimhinden skal strækkes mest ", correctAnswer: false))
        list.append(Question(text: " Hvilke(t) udsagn kan accepteres?, enlaget pladeepitel er særlig modstandsdygtigt mod mekanisk påvirkning ", correctAnswer: false))
        list.append(Question(text: " Hvilke(t) udsagn kan accepteres?, flerlaget pladeepitel er udstyret med kinocilier ", correctAnswer: false))
        list.append(Question(text: " Hvilke(t) udsagn kan accepteres?, urinblæren er beklædt med flerlaget pladeepitel ", correctAnswer: false))
        
        list.append(Question(text: " Mesotel, beklæder hjertets ydre overflade ", correctAnswer: true))
        list.append(Question(text: " Mesotel, består udelukkende af kerneløse pladeformede celler", correctAnswer: false))
        list.append(Question(text: " Mesotel, består både af kerneløse og kerneholdige pladeformede celler ", correctAnswer: false))
        list.append(Question(text: " Mesotel, beklæder seneskedernes indre overflade ", correctAnswer: false))
        list.append(Question(text: " Mesotel, danner inderste beklædning i lymfekar ", correctAnswer: false))
        
        list.append(Question(text: " Dækepitel i, seneskeder er flerlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Dækepitel i, urinblæren hedder mesotel ", correctAnswer: false))
        list.append(Question(text: " Dækepitel i, seneskeder er flerlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Dækepitel i, seneskeder er flerlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Dækepitel i, seneskeder er flerlaget pladeepitel ", correctAnswer: false))
        
        
        list.append(Question(text: " Et prismatisk dækepitel kaldes enlaget fordi, kun de prismatiske celler når basalmembranen ", correctAnswer: false))
        list.append(Question(text: " Et prismatisk dækepitel kaldes enlaget fordi, alle celler når lumen ", correctAnswer: false))
        list.append(Question(text: " Et prismatisk dækepitel kaldes enlaget fordi, ", correctAnswer: false))
        list.append(Question(text: " Et prismatisk dækepitel kaldes enlaget fordi, hver celle indeholder én kerne ", correctAnswer: false))
        list.append(Question(text: " Et prismatisk dækepitel kaldes enlaget fordi, alle celler når basalmembranen ", correctAnswer: true))
        
        list.append(Question(text: " Om flerlaget pladeepitel gælder, at det, udelukkende består af pladeformede celler ", correctAnswer: false))
        list.append(Question(text: " Om flerlaget pladeepitel gælder, at det, har kinocilier ", correctAnswer: false))
        list.append(Question(text: " Om flerlaget pladeepitel gælder, at det, udelukkende består af pladeformede celler ", correctAnswer: false))
        list.append(Question(text: " Om flerlaget pladeepitel gælder, at det, udelukkende består af pladeformede celler ", correctAnswer: false))
        list.append(Question(text: " Om flerlaget pladeepitel gælder, at det, udelukkende består af pladeformede celler ", correctAnswer: false))
        
        list.append(Question(text: " Mesotel findes i, lymfekar ", correctAnswer: false))
        list.append(Question(text: " Mesotel findes i, seneskeder", correctAnswer: false))
        list.append(Question(text: " Mesotel findes i, led ",correctAnswer: false))
        list.append(Question(text: " Mesotel findes i, bughinde " ,correctAnswer: true))
        list.append(Question(text: " Mesotel findes i, lungehinde",correctAnswer: true))
        
        list.append(Question(text: " Et flerradet epitel, har altid cellekernerne i flere rækker", correctAnswer: true))
        list.append(Question(text: " Et flerradet epitel, vil altid være enlaget ", correctAnswer: true))
        list.append(Question(text: " Et flerradet epitel, består af celler, der alle når lumen" ,correctAnswer: false))
        list.append(Question(text: " Et flerradet epitel, består kun af flade celler " ,correctAnswer: false))
        list.append(Question(text: " Et flerradet epitel, kan kun være flerlaget ",correctAnswer: false))
        
        list.append(Question(text: " Overflader, gennem hvilke der optages næringsstoffer, er beklædt med, kan kun være flerlaget , " ,correctAnswer: false))
        
        list.append(Question(text: " Overflader, gennem hvilke der optages næringsstoffer, er beklædt med, enlaget enradet prismatisk epitel", correctAnswer: true))
        list.append(Question(text: " Overflader, gennem hvilke der optages næringsstoffer, er beklædt med, enlaget kubisk epitel ", correctAnswer: false))
        list.append(Question(text: " Overflader, gennem hvilke der optages næringsstoffer, er beklædt med, flerlaget pladeepitel uden forhorning ", correctAnswer: false))
        list.append(Question(text: " Overflader, gennem hvilke der optages næringsstoffer, er beklædt med, enlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Overflader, gennem hvilke der optages næringsstoffer, er beklædt med, overgangsepitel, der kan strækkes enormt ", correctAnswer: false))
        
        list.append(Question(text: " I urinblæren findes, flerlaget kubisk epitel", correctAnswer: true))
        list.append(Question(text: " I urinblæren findes, enlaget, flerradet prismatisk epitel med fimrehår ", correctAnswer: false))
        list.append(Question(text: " I urinblæren findes, flerlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " I urinblæren findes, overgangsepitel", correctAnswer: true))
        
        list.append(Question(text: " Forhorning findes i, flerlaget prismatisk epitel ", correctAnswer: false))
        list.append(Question(text: " Forhorning findes i, flerlaget kubisk epitel ", correctAnswer: false))
        list.append(Question(text: " Forhorning findes i, mesotel ", correctAnswer: false))
        list.append(Question(text: " Forhorning findes i, flerlaget pladeepitel ", correctAnswer: true))
        list.append(Question(text: " Forhorning findes i, endotel ", correctAnswer: false))
        
        list.append(Question(text: " Endotel beklæder, lungealveolernes vægge ", correctAnswer: false))
        list.append(Question(text: " Endotel beklæder, bagsiden af hornhinden ", correctAnswer: false))
        list.append(Question(text: " Endotel beklæder, bughinden", correctAnswer: false))
        list.append(Question(text: " Endotel beklæder, indsiden af hjertet ", correctAnswer: true))
        list.append(Question(text: " Endotel beklæder, lymfekar ", correctAnswer: true))
        
        list.append(Question(text: " Den dominerende celletype på billedet findes I, urinleder ", correctAnswer: false))
        list.append(Question(text: " Den dominerende celletype på billedet findes I, urinleder ", correctAnswer: false))
        list.append(Question(text: " Den dominerende celletype på billedet findes I, luftrør  ", correctAnswer: false))
        list.append(Question(text: " Den dominerende celletype på billedet findes I, mavesæk ", correctAnswer: true))
        list.append(Question(text: " Den dominerende celletype på billedet findes I, spiserør ", correctAnswer: false))
        
        list.append(Question(text: " Fælles for flerlaget pladeepitel og flerlaget kubisk epitel er, at begge former, benævnes efter de overfladiske celler ", correctAnswer: true))
        list.append(Question(text: " Fælles for flerlaget pladeepitel og flerlaget kubisk epitel er, at begge former, har kernerne liggende i flere rader ", correctAnswer: true))
        list.append(Question(text: " Fælles for flerlaget pladeepitel og flerlaget kubisk epitel er, at begge former, mangler nerver ", correctAnswer: false))
        list.append(Question(text: " Fælles for flerlaget pladeepitel og flerlaget kubisk epitel er, at begge former, kan forhorne ", correctAnswer: false))
        list.append(Question(text: " Fælles for flerlaget pladeepitel og flerlaget kubisk epitel er, at begge former, findes i tarmen", correctAnswer: false))
        
        list.append(Question(text: " Betegnelsen flerradet anvendes om en bestemt form for, enlaget kubisk epitel ", correctAnswer: false))
        list.append(Question(text: " Betegnelsen flerradet anvendes om en bestemt form for, mesotel ", correctAnswer: false))
        list.append(Question(text: " Betegnelsen flerradet anvendes om en bestemt form for, endotel ", correctAnswer: false))
        list.append(Question(text: " Betegnelsen flerradet anvendes om en bestemt form for, enlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Betegnelsen flerradet anvendes om en bestemt form for, enlaget prismatisk epitel ", correctAnswer: true))
        
        list.append(Question(text: " Epitelbeklædningen i, ledhuler hedder endotel ", correctAnswer: false))
        list.append(Question(text: " Epitelbeklædningen i, karvægge kaldes mesotel ", correctAnswer: false))
        list.append(Question(text: " Epitelbeklædningen i, blærens væg er overgangsepitel ", correctAnswer: true))
        list.append(Question(text: " Epitelbeklædningen i, mundhulen er flerlaget pladeepitel ", correctAnswer: true))
        list.append(Question(text: " Epitelbeklædningen i, tarmen er forsynet med kinocilier ", correctAnswer: false))
        
        list.append(Question(text: " Endotel findes i, blodkar ", correctAnswer: true))
        list.append(Question(text: " Endotel findes i, bughinde  ", correctAnswer: false))
        list.append(Question(text: " Endotel findes i, seneskeder ", correctAnswer: false))
        list.append(Question(text: " Endotel findes i, lymfekar ", correctAnswer: true))
        list.append(Question(text: " Endotel findes i, led", correctAnswer: false))
        
        list.append(Question(text: " Dækepitel findes på de fleste overflader, undtagen i, ledhuler ", correctAnswer: true))
        list.append(Question(text: " Dækepitel findes på de fleste overflader, undtagen i, galdeganger ", correctAnswer: false))
        list.append(Question(text: " Dækepitel findes på de fleste overflader, undtagen i, seneskeder ", correctAnswer: true))
        list.append(Question(text: " Dækepitel findes på de fleste overflader, undtagen i, bronchier  ", correctAnswer: false))
        list.append(Question(text: " Dækepitel findes på de fleste overflader, undtagen i, kar ", correctAnswer: false))
        
        list.append(Question(text: " Et enlaget dækepitel kan være flerradet, når det drejer sig om, overgangsepitel", correctAnswer: false))
        list.append(Question(text: " Et enlaget dækepitel kan være flerradet, når det drejer sig om, prismatisk epitel ", correctAnswer: true))
        list.append(Question(text: " Et enlaget dækepitel kan være flerradet, når det drejer sig om, kubisk epitel ", correctAnswer: false))
        list.append(Question(text: " Et enlaget dækepitel kan være flerradet, når det drejer sig om, pladeepitel ", correctAnswer: false))
        list.append(Question(text: " Et enlaget dækepitel kan være flerradet, når det drejer sig om, et epitel med forhorning ", correctAnswer: false))
        
        list.append(Question(text: " Overgangsepitel er, prismatisk ", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel er, kubisk ", correctAnswer: true))
        list.append(Question(text: " Overgangsepitel er, enlaget ", correctAnswer: false))
        list.append(Question(text: " Overgangsepitel er, flerlaget", correctAnswer: true))
        list.append(Question(text: " Overgangsepitel er, pladeepitel ", correctAnswer: false))
        
        list.append(Question(text: " Enlaget pladeepitel, består af pladeformede celler med kerne ", correctAnswer: true))
        list.append(Question(text: " Enlaget pladeepitel, beklæder indsiden af seneskeder ", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, danner væg i ledhuler ", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, består af kerneløse plader", correctAnswer: false))
        list.append(Question(text: " Enlaget pladeepitel, kan forhorne ", correctAnswer: false))
        
        list.append(Question(text: " For flerlaget pladeepitel gælder at:, Det keratiniserede lag består af levende celler ", correctAnswer: false))
        list.append(Question(text: " For flerlaget pladeepitel gælder at:, Der er stamceller i alle lagene i forhornet mucosa ", correctAnswer: false))
        list.append(Question(text: " For flerlaget pladeepitel gælder at:, Når stamceller slipper basalmembranen går deres synteseapparat straks i stå ", correctAnswer: false))
        list.append(Question(text: " For flerlaget pladeepitel gælder at:, Ud mod overfladen undergår cellernes kerner apoptose ", correctAnswer: true))
        list.append(Question(text: " For flerlaget pladeepitel gælder at:, Stamceller differentierer i det keratiniserede lag ", correctAnswer: false))
        
        list.append(Question(text: " Flerlaget pladeepitel er den vigtigste eller eneste dækepiteltype i, pars nasalis pharyngis", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel er den vigtigste eller eneste dækepiteltype i, oesofagus ", correctAnswer: true))
        list.append(Question(text: " Flerlaget pladeepitel er den vigtigste eller eneste dækepiteltype i, urinleder ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel er den vigtigste eller eneste dækepiteltype i, pars postsulcalis af dorsum linguae", correctAnswer: true))
        list.append(Question(text: " Flerlaget pladeepitel er den vigtigste eller eneste dækepiteltype i, trachea ", correctAnswer: false))
        
        list.append(Question(text: " Flerlaget pladeepitel har navn efter formen af, cellerne midt i laget ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel har navn efter formen af, cellerne nær basalmembranen ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel har navn efter formen af, ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel har navn efter formen af, flade celler i varierende afstand fra basalmembranen ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel har navn efter formen af, cellerne nær overfladen ", correctAnswer: true))
        
        list.append(Question(text: " Bindevævet under dækepitel, beskytter epitelet mod slitage ", correctAnswer: false))
        list.append(Question(text: " Bindevævet under dækepitel, danner nye epitelceller, der erstatter afslidte  ", correctAnswer: false))
        list.append(Question(text: " Bindevævet under dækepitel, har betydning for epitelets ernæring  ", correctAnswer: true))
        list.append(Question(text: " Bindevævet under dækepitel, indeholder hårkar, der fortsætter op i epitelet  ", correctAnswer: false))
        list.append(Question(text: " Bindevævet under dækepitel, støtter epitelet ", correctAnswer: true))
        
        list.append(Question(text: " Flerlaget pladeepitel er særlig velegnet til at, optage næringsstoffer ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel er særlig velegnet til at, beskytte mod mekanisk påvirkning ", correctAnswer: true))
        list.append(Question(text: " Flerlaget pladeepitel er særlig velegnet til at, secernere serøst spyt ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel er særlig velegnet til at, resorbere væske ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel er særlig velegnet til at, danne slim ", correctAnswer: false))
        
        list.append(Question(text: " Dækepitel indeholder, lymfekapillærer", correctAnswer: false))
        list.append(Question(text: " Dækepitel indeholder, små arterier og vener ", correctAnswer: false))
        list.append(Question(text: " Dækepitel indeholder, blodkapillærer ", correctAnswer: false))
        list.append(Question(text: " Dækepitel indeholder, nervetråde ", correctAnswer: true))
        list.append(Question(text: " Dækepitel indeholder, lymfekar ", correctAnswer: false))
        
        list.append(Question(text: " Flerlaget pladeepitel har især betydning for, rensning af en luftstrøm  ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel har især betydning for, sekretion ", correctAnswer: false))
        list.append(Question(text: " Flerlaget pladeepitel har især betydning for, resorption ", correctAnswer: false))
        list.append(Question(text: "Flerlaget pladeepitel har især betydning for, beskyttelse", correctAnswer: true))
        list.append(Question(text: "Flerlaget pladeepitel har især betydning for, transport af et slimlag  ", correctAnswer: false))
        
        list.append(Question(text: "Overgangsepitel er et flerlaget kubisk epitel, fordi der findes kubiske celler, luminalt  ", correctAnswer: true))
        list.append(Question(text: "Overgangsepitel er et flerlaget kubisk epitel, fordi der findes kubiske celler, spredt i alle lag  ", correctAnswer: false))
        list.append(Question(text: "Overgangsepitel er et flerlaget kubisk epitel, fordi der findes kubiske celler, i de midterste lag   ", correctAnswer: false))
        list.append(Question(text: "Overgangsepitel er et flerlaget kubisk epitel, fordi der findes kubiske celler, ", correctAnswer: false))
        list.append(Question(text: "Overgangsepitel er et flerlaget kubisk epitel, fordi der findes kubiske celler, basalt", correctAnswer: false))
        
        list.append(Question(text: "Om flerlagede epitelier gælder, at de, benævnes efter formen af de overfladiske celler ", correctAnswer: true))
        list.append(Question(text: "Om flerlagede epitelier gælder, at de, alle kan secernere slim  ", correctAnswer: false))
        list.append(Question(text: "Om flerlagede epitelier gælder, at de, indeholder kar i de lag, der ligger nærmest bindevævet ", correctAnswer: false))
        list.append(Question(text: "Om flerlagede epitelier gælder, at de, samtidig er flerradede", correctAnswer: true))
        list.append(Question(text: "Om flerlagede epitelier gælder, at de, er velegnede til resorption ", correctAnswer: false))
        
        list.append(Question(text: "Overflader, der er udsat for særlig stærkt slid, er beklædt med, epitel, der er særlig plastisk ", correctAnswer: false))
        list.append(Question(text: "Overflader, der er udsat for særlig stærkt slid, er beklædt med, enlaget enradet prismatisk epitel med lange, stive og ubevægelige cytoplasmaudløbere ", correctAnswer: false))
        list.append(Question(text: "Overflader, der er udsat for særlig stærkt slid, er beklædt med, flerlaget pladeepitel uden forhorning ", correctAnswer: true))
        list.append(Question(text: "Overflader, der er udsat for særlig stærkt slid, er beklædt med, enlaget flerradet prismatisk epitel med kraftige kinocilier, der kan transportere et beskyttende slimlag", correctAnswer: false))
        list.append(Question(text: "Overflader, der er udsat for særlig stærkt slid, er beklædt med, flerlaget pladeepitel med forhorning", correctAnswer: true))
        
        list.append(Question(text: "Celler af meget forskellig højde kan forekomme I, endotel ", correctAnswer: false))
        list.append(Question(text: "Celler af meget forskellig højde kan forekomme I, enlaget prismatisk epitel  ", correctAnswer: true))
        list.append(Question(text: "Celler af meget forskellig højde kan forekomme I, enlaget pladeepitel, der ikke tilhører (A) eller (B) ", correctAnswer: false))
        list.append(Question(text: "Celler af meget forskellig højde kan forekomme I, mesotel ", correctAnswer: false))
        list.append(Question(text: "Celler af meget forskellig højde kan forekomme I, enlaget kubisk epitel", correctAnswer: false))
        
        list.append(Question(text: "Fimrehår, er selvbevægelige", correctAnswer: true))
        list.append(Question(text: "Fimrehår, kan deltage i optagelse af stoffer fra lumen ", correctAnswer: false))
        list.append(Question(text: "Fimrehår, har betydning for sekretion", correctAnswer: false))
        list.append(Question(text: "Fimrehår, består af cytoplasmaudløbere ", correctAnswer: true))
        list.append(Question(text: "Fimrehår, fungerer som føleantenner for cellerne ", correctAnswer: false))
        
        list.append(Question(text: "Epitelceller med fimrehår findes I, tarm  ", correctAnswer: false))
        list.append(Question(text: "Epitelceller med fimrehår findes I, urinveje  ", correctAnswer: false))
        list.append(Question(text: "Epitelceller med fimrehår findes I, luftveje  ", correctAnswer: true))
        list.append(Question(text: "Epitelceller med fimrehår findes I, spiserør", correctAnswer: false))
        list.append(Question(text: "Epitelceller med fimrehår findes I, mundhule", correctAnswer: false))
        
        list.append(Question(text: "Om dækepitel gælder at, overgangsepitel er meget plastisk ", correctAnswer: true))
        list.append(Question(text: "Om dækepitel gælder at, endotel beklæder bronchierne ", correctAnswer: false))
        list.append(Question(text: "Om dækepitel gælder at, tarmens epitel er forsynet med fimrehår, der kan bevæge et slimtæppe", correctAnswer: false))
        list.append(Question(text: "Om dækepitel gælder at, mesotel har mange cytoplasmaudløbere, der gør det velegnet til sekretion", correctAnswer: false))
        list.append(Question(text: "Om dækepitel gælder at, flerlaget pladeepitel er særlig egnet til resorption", correctAnswer: false))
        
        list.append(Question(text: "Det mest plastiske dækepitel er, mesotel ", correctAnswer: false))
        list.append(Question(text: "Det mest plastiske dækepitel er, flerlaget pladeepitel  ", correctAnswer: false))
        list.append(Question(text: "Det mest plastiske dækepitel er, endotel  ", correctAnswer: false))
        list.append(Question(text: "Det mest plastiske dækepitel er, enlaget kubisk epitel ", correctAnswer: false))
        list.append(Question(text: "Det mest plastiske dækepitel er, flerlaget kubisk epitel  ", correctAnswer: true))
        
        
        list.append(Question(text: "Endotel, er altid uforhornet", correctAnswer: true))
        list.append(Question(text: "Endotel, bærer fimrehår ", correctAnswer: false))
        list.append(Question(text: "Endotel, findes i lymfekar ", correctAnswer: true))
        list.append(Question(text: "Endotel, er et tyndt flerlaget pladeepitel ", correctAnswer: false))
        list.append(Question(text: "Endotel, består af kubiske celler ", correctAnswer: false))
        
    }
}



